const COPY = {
  en: {
    popup: {
      eyebrow: 'Chrome Extension MVP',
      title: 'Maestro Player',
      subtitle: 'Use the current GitHub or GitLab repository tab as the next public replay seed.',
      urlLabel: 'Public repository URL',
      playButton: 'Play This Repo',
      openPlayerButton: 'Open Player',
      ready: 'Repository detected. Launch the player tab when ready.',
      idle: 'Paste a public GitHub or GitLab repository URL to seed the player.',
      invalidUrl: 'Enter a supported public GitHub or GitLab repository URL.',
      launching: 'Opening the Maestro Player extension page...',
      launchFailed: 'Failed to launch the player tab.',
      openingPlayer: 'Opening the Maestro Player tab...',
      openPlayerFailed: 'Failed to open the player tab.',
      detectedRepository: (provider, repoSlug) => `Detected from current tab: ${repoSlug} (${provider})`,
      lastLaunch: (repoSlug) => `Last launched repository: ${repoSlug}`,
      noRepositoryDetected: 'No supported repository was detected in the current tab.',
    },
    player: {
      eyebrow: 'Read-Only Repo Session',
      title: 'Maestro Player Extension',
      subtitle: 'This scaffold stores the selected public repository seed and prepares the extension surface for the full rhythm shell.',
      selectedRepoTitle: 'Selected Repository',
      selectedRepoCopy: 'The popup writes the latest public repo selection here before the player flow is mounted.',
      repoLabel: 'Repository',
      branchLabel: 'Branch',
      sourceLabel: 'Launch source',
      urlTitle: 'Canonical URL',
      openRepoButton: 'Open Repository',
      refreshButton: 'Refresh Session',
      clearButton: 'Clear Session',
      scaffoldTitle: 'Current Scaffold',
      scaffoldItems: [
        'MV3 popup, background, and player page handoff.',
        'Current-tab GitHub and GitLab repository detection.',
        'Canonical public repo URL normalization for extension launch.',
        'Local launch-session persistence through chrome.storage.local.',
      ],
      nextTitle: 'Next Integration Steps',
      nextItems: [
        'Mount the existing React player shell into player.html.',
        'Inject the stored repo seed into the public replay loader.',
        'Restore golden listening demos and autoplay preview inside the extension.',
        'Add token-based connected account mode after public flow is stable.',
      ],
      sessionTitle: 'Stored Launch Session',
      awaitingLaunch: 'No repo seed has been launched yet. Use the popup on a public repository page first.',
      loaded: (label) => `Loaded repo seed: ${label}`,
      refreshed: 'Launch session refreshed.',
      cleared: 'Launch session cleared.',
      missingRepository: 'No repository is stored yet.',
      pendingLabel: 'pending',
      emptyValue: '-',
    },
  },
  ko: {
    popup: {
      eyebrow: '크롬 익스텐션 MVP',
      title: 'Maestro Player',
      subtitle: '현재 GitHub 또는 GitLab 저장소 탭을 다음 public replay seed로 넘긴다.',
      urlLabel: '공개 저장소 URL',
      playButton: '이 저장소 재생',
      openPlayerButton: '플레이어 열기',
      ready: '저장소를 감지했다. 준비되면 플레이어 탭을 연다.',
      idle: 'public player seed로 쓸 GitHub 또는 GitLab 저장소 URL을 넣어라.',
      invalidUrl: '지원되는 GitHub 또는 GitLab 공개 저장소 URL을 입력해라.',
      launching: 'Maestro Player 익스텐션 페이지를 여는 중...',
      launchFailed: '플레이어 탭을 열지 못했다.',
      openingPlayer: 'Maestro Player 탭을 여는 중...',
      openPlayerFailed: '플레이어 탭을 열지 못했다.',
      detectedRepository: (provider, repoSlug) => `현재 탭에서 감지됨: ${repoSlug} (${provider})`,
      lastLaunch: (repoSlug) => `최근 실행 저장소: ${repoSlug}`,
      noRepositoryDetected: '현재 탭에서 지원되는 저장소를 찾지 못했다.',
    },
    player: {
      eyebrow: '읽기 전용 저장소 세션',
      title: 'Maestro Player Extension',
      subtitle: '이 스캐폴드는 선택한 public 저장소 seed를 저장하고, 전체 리듬 플레이어 셸을 올릴 자리를 준비한다.',
      selectedRepoTitle: '선택된 저장소',
      selectedRepoCopy: 'popup이 최신 public 저장소 선택값을 여기에 기록하고, 그 다음에 플레이어 플로우를 마운트한다.',
      repoLabel: '저장소',
      branchLabel: '브랜치',
      sourceLabel: '실행 경로',
      urlTitle: '정규화 URL',
      openRepoButton: '저장소 열기',
      refreshButton: '세션 새로고침',
      clearButton: '세션 비우기',
      scaffoldTitle: '현재 스캐폴드 범위',
      scaffoldItems: [
        'MV3 popup, background, player page handoff.',
        '현재 탭 GitHub/GitLab 저장소 감지.',
        '익스텐션 실행용 public repo URL 정규화.',
        'chrome.storage.local 기반 launch session 저장.',
      ],
      nextTitle: '다음 통합 단계',
      nextItems: [
        '기존 React player shell을 player.html에 마운트한다.',
        '저장된 repo seed를 public replay loader 초기값으로 주입한다.',
        'golden listening demo와 autoplay preview를 익스텐션 안으로 복원한다.',
        'public 흐름이 안정화된 뒤 token 기반 account mode를 넣는다.',
      ],
      sessionTitle: '저장된 Launch Session',
      awaitingLaunch: '아직 실행된 repo seed가 없다. 먼저 public 저장소 페이지에서 popup을 사용해라.',
      loaded: (label) => `로드된 repo seed: ${label}`,
      refreshed: 'launch session을 새로고침했다.',
      cleared: 'launch session을 비웠다.',
      missingRepository: '저장된 저장소가 아직 없다.',
      pendingLabel: '대기',
      emptyValue: '-',
    },
  },
};

export function resolveExtensionLanguage(language) {
  return String(language || '').toLowerCase().startsWith('ko') ? 'ko' : 'en';
}

export function getExtensionCopy(language) {
  return COPY[resolveExtensionLanguage(language)];
}
